## Manejo de Errores ##

num1 = 5
num2 = "1"

try:
    print(num1 + num2)
except:
    print("No se pudo hacer la operaci√≥n")